### ISSUE TITLE
Curl

### ISSUE THREAD

**Issue by lucidyan** [REDNBLACK/Kinopoisk2IMDB#5]
После установки php и composer через apt-get, требуется еще и curl
Нужно вручную выполнить для ubuntu: (добавьте, пожалуйста, в man)
 sudo apt-get install curl libcurl3 libcurl3-dev php5-curl

**Comment by REDNBLACK** [comment]
Хм, думал он входит в стандартную поставку.
Допишу в доки в следующей версии.
