### ISSUE TITLE
Проблема с русскими названиями

### ISSUE THREAD

**Issue by lucidyan** [REDNBLACK/Kinopoisk2IMDB#6]
В логе неимпортированных фильмов не отображаются русские названия: (fish, ubuntu 15.10)
Пример:
При обработке произошли ошибки со следующими фильмами:
+-----------------------------------------------+------+---------+-----------------+
| Название                                      | Год  | Рейтинг | Ошибка          |
+-----------------------------------------------+------+---------+-----------------+
|                                               | 1972 | 9       | movie_not_found |
| Vincent                                       | 1982 | 8       | movie_not_found |
| Crna mačka, beli mačor                        | 1998 | 9       | movie_not_found |
| Blowup                                        | 1966 | 7       | movie_not_found |
|                                               | 2001 | 7       | movie_not_found |
|                                               | 2000 | 7       | movie_not_found |
| Le Fabuleux destin d'Amelie Poulain           | 2001 | 7       | movie_not_found |
|                                               | 1997 | 7       | movie_not_found |
|                                               | 1976 | 7       | movie_not_found |
|                                               | 2006 | 7       | movie_not_found |
|                                               | 2007 | 7       | movie_not_found |
|                                               | 1977 | 6       | movie_not_found |
| Heart Beat                                    | 1980 | 6       | movie_not_found |
|                                               | 1986 | 7       | movie_not_found |
|                                               | 1965 | 6       | movie_not_found |
| Malice in Wonderland                          | 1982 | 6       | movie_not_found |
| Restless                                      | 2011 | 7       | movie_not_found |
|                                               | 1983 | 6       | movie_not_found |
|                                               | 2011 | 6       | movie_not_found |
| Mr. Nice                                      | 2010 | 6       | movie_not_found |
|                                               | 1988 | 7       | movie_not_found |
|                                               | 1983 | 7       | movie_not_found |
| Malice in Wonderland                          | 2009 | 7       | movie_not_found |
| Frankenweenie                                 | 1984 | 7       | movie_not_found |
|                                               | 1964 | 8       | movie_not_found |
|                                               | 1965 | 9       | movie_not_found |
|                                               | 1964 | 8       | movie_not_found |
|                                               | 1991 | 7       | movie_not_found |
|                                               | 1966 | 7       | movie_not_found |
|                                               | 2006 | 8       | movie_not_found |
|                                               | 1982 | 7       | movie_not_found |
|                                               | 1960 | 9       | movie_not_found |
| Masculin feminin                              | 1966 | 7       | movie_not_found |
| Dekalog                                       | 1988 | 10      | movie_not_found |
|                                               | 1989 | 8       | movie_not_found |
|                                               | 1987 | 7       | movie_not_found |
| Celda 211                                     | 2009 | 7       | movie_not_found |
|                                               | 1982 | 8       | movie_not_found |
|                                               | 2008 | 7       | movie_not_found |
|                                               | 1967 | 6       | movie_not_found |
|                                               | 2011 | 8       | movie_not_found |
| Cria cuervos                                  | 1975 | 8       | movie_not_found |
|                                               | 1961 | 8       | movie_not_found |
| Interstate 60                                 | 2001 | 8       | movie_not_found |
|                                               | 2001 | 7       | movie_not_found |
|                                               | 2005 | 7       | movie_not_found |
|                                               | 2009 | 6       | movie_not_found |
|                                               | 1987 | 7       | movie_not_found |
|                                               | 1988 | 7       | movie_not_found |
| Le notti di Cabiria                           | 1957 | 7       | movie_not_found |
|                                               | 1987 | 7       | movie_not_found |
| $9.99                                         | 2008 | 8       | movie_not_found |
|                                               | 1989 | 7       | movie_not_found |
|                                               | 1993 | 6       | movie_not_found |
| Clerks.                                       | 1994 | 5       | movie_not_found |
|                                               | 2006 | 6       | movie_not_found |
|                                               | 1957 | 7       | movie_not_found |
|                                               | 2011 | 1       | movie_not_found |
|                                               | 1972 | 7       | movie_not_found |
| Hostsonaten                                   | 1978 | 7       | movie_not_found |
|                                               | 1927 | 8       | movie_not_found |
|                                               | 1979 | 8       | movie_not_found |
| Karamazovi                                    | 2008 | 8       | movie_not_found |
|                                               | 1966 | 8       | movie_not_found |
|                                               | 1969 | 8       | movie_not_found |
|                                               | 1957 | 8       | movie_not_found |
|                                               | 2003 | 8       | movie_not_found |
|                                               | 2012 | 8       | movie_not_found |
|                                               | 2003 | 9       | movie_not_found |
| Pribehy obycejneho silenstvi                  | 2005 | 7       | movie_not_found |
|                                               | 2014 | 5       | movie_not_found |
|                                               | 1995 | 7       | movie_not_found |
|                                               | 1988 | 8       | movie_not_found |
| Pierrot le fou                                | 1965 | 7       | movie_not_found |
| Dzień świra                                   | 2002 | 7       | movie_not_found |
| L'illusionniste                               | 2010 | 6       | movie_not_found |
| Legend of the Guardians: The Owls of Ga’Hoole | 2010 | 7       | movie_not_found |
| Lundi matin                                   | 2002 | 7       | movie_not_found |
| Warum lauft Herr R. Amok                      | 1970 | 6       | movie_not_found |
|                                               | 1961 | 6       | movie_not_found |
| Rose Red                                      | 2002 | 5       | movie_not_found |
| Leon                                          | 1994 | 6       | movie_not_found |
| La vie de boheme                              | 1992 | 8       | movie_not_found |
| Le professionnel                              | 1981 | 6       | movie_not_found |
|                                               | 1988 | 7       | movie_not_found |
|                                               | 1975 | 7       | movie_not_found |
| Idioot                                        | 2011 | 7       | movie_not_found |
| Ben X                                         | 2007 | 5       | movie_not_found |
|                                               | 1971 | 1       | movie_not_found |
| Yip Man                                       | 2008 | 6       | movie_not_found |
|                                               | 1979 | 6       | movie_not_found |
|                                               | 2014 | 7       | movie_not_found |
|                                               | 2008 | 6       | movie_not_found |
|                                               | 1967 | 6       | movie_not_found |
|                                               | 1963 | 6       | movie_not_found |
| La Pianiste                                   | 2001 | 7       | movie_not_found |
| Przypadek                                     | 1981 | 7       | movie_not_found |
| Burroughs                                     | 1983 | 7       | movie_not_found |
|                                               | 2014 | 6       | movie_not_found |
|                                               | 2015 | 8       | movie_not_found |
|                                               | 2009 | 6       | movie_not_found |
|                                               | 1995 | 6       | movie_not_found |
|                                               | 2001 | 6       | movie_not_found |
|                                               | 1968 | 5       | movie_not_found |
|                                               | 2006 | 8       | movie_not_found |
|                                               | 2014 | 1       | movie_not_found |
| Panda kopanda                                 | 1972 | 7       | movie_not_found |
| Das Cabinet des Dr. Caligari                  | 1920 | 8       | movie_not_found |
|                                               | 1970 | 8       | movie_not_found |
|                                               | 2010 | 7       | movie_not_found |
|                                               | 2014 | 6       | movie_not_found |
|                                               | 2003 | 8       | movie_not_found |
|                                               | 2014 | 1       | movie_not_found |
|                                               | 2012 | 7       | movie_not_found |
| Oslo, 31. august                              | 2011 | 7       | movie_not_found |
|                                               | 2014 | 7       | movie_not_found |
|                                               | 2000 | 6       | movie_not_found |
|                                               | 2003 | 7       | movie_not_found |
| Šileni                                        | 2005 | 8       | movie_not_found |
|                                               | 2009 | 7       | movie_not_found |
| L'idiot                                       | 2008 | 8       | movie_not_found |
|                                               | 1999 | 10      | movie_not_found |
| The Freshman                                  | 1925 | 7       | movie_not_found |
|                                               | 2012 | 4       | movie_not_found |
+-----------------------------------------------+------+---------+-----------------+

**Comment by REDNBLACK** [comment]
Подтверждено, действительно косяк, ниразу не тестировал на русских фильмах.

**Comment by REDNBLACK** [comment]
Могу я попросить выслать мне на почту (указана в профиле) большой список российских фильмов (штук 100 хотя бы) в формате xls?
Ошибка проявляется не везде.

**Comment by REDNBLACK** [comment]
Вобщем я починил их, но IMDB сам по себе, через API не находит ни одного русскоязычного фильма. 

К примеру
`http://www.imdb.com/xml/find?q=Белое солнце пустыни&tt=on&nr=1&json=1`
и `http://www.imdb.com/xml/find?q=Белое солнце пустыни&tt=on&nr=1`
ничего не найдут, хотя при поиске тут
`http://www.imdb.com/find?q=Белое солнце пустыни&s=tt&exact=true`
находит.

Постараюсь в следующем обновление прикрутить опцию поиска и парсинга через HTML, а пока закрываю.

**Comment by REDNBLACK** [comment]
Добавил парсинг HTML в новой версии.
