### ISSUE TITLE
Network problem

### ISSUE THREAD

**Issue by morhine** [REDNBLACK/Kinopoisk2IMDB#7]
Приветствую!

Пробовал вчера дважды экспортировать оценки. В конце выводится список фильмов с оценками и напротив каждой Network Problem:
| Star Wars: The Force Awakens                                                      | 2015 | 9       | network_problem
: 403 |

**Comment by REDNBLACK** [comment]
Вы неправильно указали строку авторизации (auth). Не ошибка программы.

**Comment by morhine** [comment]
Да, спасибо. Почему-то из Chrome'а не весь ID скопировался. Всё прошло нормально. Спасибо!

**Comment by REDNBLACK** [comment]
Чтобы удобно скопировать из хрома, нужно сделать тройной клик левой кнопкой мыши и потом нажать Ctrl + C.
